POST http://localhost:8080/api/item
Content-Type: text/html

<mjml>
    <mj-body>
        <mj-section>
            <mj-column>
                <mj-image width="100px" src="/testimage.jpg"></mj-image>
                <mj-divider border-color="#F45E43"></mj-divider>
                <mj-text font-size="20px" color="#F45E43" font-family="helvetica">teststring zürich with umlaut</mj-text>
                <mj-text font-size="20px" color="#F45E43" font-family="helvetica">Smiley: 😁</mj-text>
            </mj-column>
        </mj-section>
    </mj-body>
</mjml>
